---
name: Joakim
surname: Frögren
position: "Personligt brev"
address: "791031-7119"
profilepic: "./img/me.jpg"
www: "Edward Lindahlsgatan 9, 217 42 Malmö"
email: "joakim@frogren.se"
phone: +46 73 516 12 12
date: "`r format(Sys.time(), '%Y-%m-%d')`"
lang: "sv"
headcolor: 121270
aboutme: ""
bibliography: publications.bib
given-name-pattern: Joakim
family-name-pattern: Frögren
docname: Personligt brev
output: 
    vitae::awesomecv:
            pandoc_args: ["--lua-filter=highlight-author.lua"]

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      warning = FALSE,
                      message = FALSE)

require(xfun)

packages <- c('vitae'     # The CV's LaTeX Template
             ,'tibble'    # Data structure for tribbles
             ,'magrittr'  # The Pipe %>%
             ,'here'      # Relative File Paths
             ,'readr'     # Data Loading
             ,'glue'      # String Manipulation
            )

xfun::pkg_attach2(packages, message = FALSE)

source(file = here("r","data.r"))

```

\vspace{1.25cm} \rightline{\textcolor{gray}{19 mars 2024}}

\vspace{-0.5cm}\textcolor{gray}{Avdelningen för folkhälsovetenskap}    \
\textcolor{gray}{Fakulteten för hälsovetenskap}      \
\textcolor{gray}{Högskolan Kristianstad}      \
\textcolor{gray}{291 88 Kristianstad}      \
        
\vspace{0.25cm}\textbf{Ansökan till tjänsten som lektor i folkhälsovetenskap, ref. P2024-3711-31 }     \
\vspace{0.15cm} \textcolor{black}{}




Jag disputerade i våras med en avhandling om brukarinvolvering i forskning om åldrande och hälsa. Intresset för ämnet bottnar i mina erfarenheter av att det är betydelsefullt, inte minst ur demokratisk synvinkel, att de människor som forskning berör också ges möjlighet att vara med och påverka hur den är utformad. Det handlar till exempel om att det är adekvata och aktuella forskningsfrågor som ställs, och att de ställs på ett inkluderande sätt som inte systematiskt exkluderar vissa grupper. 

Efter intensiva doktorandstudier och erhållen examen kände jag ett behov av en paus från universitetet och har därför arbetat på ett boende för personer med psykisk sjukdom och i vissa fall en beroendeproblematik. Det har för mig varit ett välbehövligt avbrott, men jag känner nu en längtan efter mer intellektuell stimulans.
Jag är också i en livssituation där jag känner ett behov av att "landa" och att förankra mig på en arbetsplats där jag ser goda möjligheter att trivas och utvecklas under en längre tid. I lektorstjänsten inom folkhälsovetenskap vid HKR ser jag en sådan möjlighet. 

Jag har erfarenhet av att föreläsa för en rad olika målgrupper, alltifrån en intresserad allmänhet till studenter och seniora forskare. Som medlem i en nationell forskarskola under min doktorandtid var jag med och anordnade en vetenskaplig konferens. I den rollen ingick många uppgifter som påminner om en undervisningssituation på en högskola, såsom att föra dialog med inbjudna föreläsare, att introducera dem inför åhörarna och att se till så att tekniken fungerar. Inom forskarskolan fick vi som var anslutna doktorander också regelbundet öva oss på att presentera vår forskning för varandra och att komma med återkoppling på ett konstruktivt sätt.

I den nätbaserade kurs jag för tillfället läser inom medicinsk humaniora använder vi Canvas som plattform och även om jag hittills bara har erfarenhet av den från min roll som student, så är jag övertygad om att jag enkelt skulle kunna lära mig att bemästra verktyget. Sedan övergången till alltmer nätbaserade möten och seminarier i anslutning till pandemin har jag också blivit en van användare av Zoom och Microsoft Teams. 

När det kommer till mål och visioner med undervisning så tillgodose och säkerställa att studenterna får så goda kunskaper med sig som möjligt. Det är därför av stor vikt att det kollegiala samarbetet fungerar väl och att det sker i en god anda. Här är jag övertygad om att etablerandet och upprätthållandet av en god kommunikation är av största vikt. 

Jag tror att jag passar för jobbet genom att jag inte har den traditionella bakgrunden utan kan föra in lite nya perspektiv från min såväl yrkesmässiga som min utbildningsmässiga bakgrund. Under min doktorandtid jobbade jag i en rad olika forskningsprojekt och ofta med representanter för organisationer utanför akademin. Erfarenheten därifrån har övat upp min samarbetsförmåga och tränat mig i att vara flexibel eftersom det i projekt tenderar att uppstå situationer som inte går att förutspå men som måste lösas. De möjligheter men också utmaningar som ett sådant samverkansarbete innebär är något jag har såväl teoretisk som praktisk kunskap av och som jag tror är av nytta i såväl undervisning som forskning där olika former av samverkan ingår.

Yrkesmässigt är jag en person som sprider mycket glädje omkring sig och som trivs med att ha människor runt sig. Den sociala biten på en arbetsplats är mycket viktig för mig. På seminarier och möten är jag ofta den som kommer med lite finurliga frågor och invändningar, vilket brukar uppskattas. Jag är van att tala inför folk och inte särskilt blyg i mötet med nya människor. 

Jag ser fram emot att berätt amer om mig själv vid en eventuell framtida intervju.

\vspace*{0.5cm}
Vänliga hälsningar,

\vspace*{0.5cm}
\textbf{Joakim Frögren}

\vspace*{0.5cm} Bifogat: Curriculum Vitae
